export enum HCActionTypes {
    INIT_MUSIC_KIT = "INIT_MUSIC_KIT",
    LOADING_USER_LIBRARY = "LOADING_USER_LIBRARY",
    UPDATE_USER_LIBRARY = "UPDATE_USER_LIBRARY",
    UPDATE_IS_LOADING = "UPDATE_IS_LOADING",
    UPDATE_IS_AUTHORIZED = "UPDATE_IS_AUTHORIZED",
}